# Site settings
title: Abhiraj Das Ghosh (Bong Lebowski)
description: Creative Coder | Growth Marketer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Abhiraj Das Ghosh
user_description: I am a Digital Strategist, looking to upskill myself in interesting tech. Recently I have married my love for <b>Music</b> and <b>Coding</b>, I am experimenting with <a href="https://sonic-pi.net/" target="_blank"><b>Sonic Pi</b></a> and <a href="https://tidalcycles.org/" target="_blank"><b>TidalCycles</b></a> right now.
email: bonglebowski@abhirajdg.in
 twitter_username: BongLebowski
 github_username:  abhirajdg
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
